import { Link } from 'react-router-dom'; import { ArrowRight, CheckCircle2, Scale, GitCommitHorizontal, ShieldCheck, RefreshCw, FolderKanban } from 'lucide-react'; import StatusPill from '../components/StatusPill'; import { shortAddress, formatDate } from '../lib/format'
export default function Dashboard({data,wallet}){const {programs,milestones,loading,error,refresh}=data;const active=programs.filter(p=>p.status==='ACTIVE').length;const resolved=milestones.filter(m=>m.status==='RESOLVED').length;const challenged=milestones.filter(m=>m.status==='CHALLENGED').length;return <>
<section className="hero"><div><div className="eyebrow"><ShieldCheck size={15}/> GENLAYER STUDIO DEPLOYMENT</div><h1>Grant milestones deserve a <em>public seal of evidence.</em></h1><p>Lock the scope before work begins. Submit an exact Git commit. Let challengers respond, then let GenLayer independently adjudicate the milestone.</p><div className="hero-actions"><Link className="primary-btn" to="/new">Create a program <ArrowRight size={17}/></Link><Link className="secondary-btn" to="/programs">Explore programs</Link></div></div><div className="hero-card"><div className="seal"><ShieldCheck size={54}/></div><b>11-state transition workflow</b><p>Draft → locked → accepted → submitted → challenged → resolved → appealed → closed.</p><div className="evidence-row"><GitCommitHorizontal/> Exact commit binding</div><div className="evidence-row"><Scale/> Independent consensus</div></div></section>
<section className="metrics"><Metric label="Programs" value={loading?'…':programs.length} icon={<FolderKanban/>}/><Metric label="Active" value={loading?'…':active} icon={<CheckCircle2/>}/><Metric label="Resolved milestones" value={loading?'…':resolved} icon={<ShieldCheck/>}/><Metric label="Open challenges" value={loading?'…':challenged} icon={<Scale/>}/></section>
{error&&<div className="banner error">Unable to load live contract state: {error}<button onClick={refresh}><RefreshCw size={15}/> Retry</button></div>}
<section className="section-head"><div><div className="eyebrow">LIVE CONTRACT STATE</div><h2>Recent programs</h2></div><Link to="/programs">View all <ArrowRight size={16}/></Link></section>
<div className="program-grid">{loading?[1,2,3].map(i=><div className="skeleton card" key={i}/>):programs.slice(0,6).map(p=><Link className="program-card" to={`/programs/${p.program_id}`} key={p.program_id}><div className="card-top"><span className="id">PROGRAM #{p.program_id}</span><StatusPill>{p.status}</StatusPill></div><h3>{p.title}</h3><p>{p.summary}</p><div className="card-meta"><span>{p.repo_id}</span><span>{p.milestone_count} milestones</span></div><div className="card-foot"><span>{shortAddress(p.grantor)}</span><span>{formatDate(p.created_at)}</span></div></Link>)}{!loading&&!programs.length&&<Empty/>}</div>
<section className="how"><div className="section-head"><div><div className="eyebrow">THE PROTOCOL</div><h2>Built around real lifecycle steps</h2></div></div><div className="steps">{[['01','Lock','Grantor precommits repository, scope and milestones.'],['02','Submit','Recipient binds a milestone to one exact commit SHA.'],['03','Contest','A challenger may dispute the submission; the recipient may respond.'],['04','Resolve','Validators re-fetch canonical GitHub records and independently judge the locked criteria.'],['05','Appeal','A fresh consensus round can independently re-adjudicate the result.']].map(s=><div className="step" key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div></section></>}
function Metric({label,value,icon}){return <div className="metric"><div>{icon}</div><b>{value}</b><span>{label}</span></div>}; function Empty(){return <div className="empty"><FolderKanban size={30}/><h3>No programs yet</h3><p>The contract is live and ready for its first grant program.</p><Link className="primary-btn" to="/new">Create program</Link></div>}
