import { Link,useParams } from 'react-router-dom'; import { useMemo,useState } from 'react'; import { ArrowLeft, Github, LockKeyhole, CheckCircle2, Scale, Send, Gavel, RotateCcw, XCircle, ExternalLink, Clock3 } from 'lucide-react'; import StatusPill from '../components/StatusPill'; import AsyncButton from '../components/AsyncButton'; import TxNotice from '../components/TxNotice'; import { sameAddress,shortAddress,shortSha,formatDate } from '../lib/format'; import { messageFromError } from '../lib/errors'
export default function ProgramDetail({data,wallet}){const {id}=useParams();const program=data.programs.find(p=>String(p.program_id)===String(id));const ms=useMemo(()=>data.milestones.filter(m=>String(m.program_id)===String(id)).sort((a,b)=>Number(a.milestone_id)-Number(b.milestone_id)),[data.milestones,id]);const [busy,setBusy]=useState(''),[error,setError]=useState('');if(data.loading)return <div className="page"><div className="skeleton detail-skeleton"/></div>;if(!program)return <div className="page empty"><h1>Program not found</h1><p>It may not exist in the latest final state.</p><Link className="primary-btn" to="/programs">Back to programs</Link></div>;
 const grantor=sameAddress(wallet.account,program.grantor),recipient=sameAddress(wallet.account,program.recipient);const doWrite=async(fn,args)=>{setError('');setBusy(fn);try{await data.write(fn,args)}catch(e){setError(messageFromError(e))}finally{setBusy('')}};const now=Math.floor(Date.now()/1000)
 return <div className="page"><Link className="back" to="/programs"><ArrowLeft size={16}/> All programs</Link><section className="detail-hero"><div><div className="eyebrow">PROGRAM #{program.program_id}</div><div className="title-row"><h1>{program.title}</h1><StatusPill>{program.status}</StatusPill></div><p>{program.summary}</p><div className="detail-meta"><a href={`https://github.com/${program.repo_id}`} target="_blank" rel="noreferrer"><Github size={16}/>{program.repo_id}<ExternalLink size={13}/></a><span>Grantor {shortAddress(program.grantor)}</span><span>Recipient {shortAddress(program.recipient)}</span></div></div><div className="progress-box"><b>{program.resolved_milestone_count} / {program.milestone_count}</b><span>milestones terminally resolved</span><div className="progress"><i style={{width:`${Number(program.milestone_count)?Number(program.resolved_milestone_count)/Number(program.milestone_count)*100:0}%`}}/></div>{program.status==='LOCKED'&&recipient&&<AsyncButton loading={busy==='accept_program'} onClick={()=>doWrite('accept_program',[BigInt(id)])}><CheckCircle2 size={17}/> Accept program</AsyncButton>}{program.status==='ACTIVE'&&grantor&&Number(program.resolved_milestone_count)===Number(program.milestone_count)&&<AsyncButton loading={busy==='close_program'} onClick={()=>doWrite('close_program',[BigInt(id)])}><LockKeyhole size={17}/> Close program</AsyncButton>}</div></section>
 <TxNotice tx={data.tx} explorerTx={data.explorerTx}/>{error&&<div className="banner error">{error}</div>}
 <section className="lifecycle"><div><span className={program.status==='DRAFT'?'current':'done'}>1</span><b>Draft</b></div><div><span className={['LOCKED','ACTIVE','CLOSED'].includes(program.status)?'done':''}>2</span><b>Locked</b></div><div><span className={['ACTIVE','CLOSED'].includes(program.status)?'done':''}>3</span><b>Accepted</b></div><div><span className={program.status==='CLOSED'?'done':''}>4</span><b>Closed</b></div></section>
 <section className="section-head"><div><div className="eyebrow">MILESTONE REGISTRY</div><h2>Locked acceptance criteria</h2></div>{recipient&&program.status==='ACTIVE'&&<span className="role-note">You are the recipient</span>}{grantor&&<span className="role-note">You are the grantor</span>}</section>
 <div className="milestone-list">{ms.map(m=><MilestoneCard key={m.milestone_id} m={m} program={program} wallet={wallet} busy={busy} doWrite={doWrite} now={now}/>)}</div>{!ms.length&&<div className="empty"><h3>No milestones</h3><p>This program has not defined any milestone records.</p></div>}
 <section className="audit-strip"><div><b>On-chain timestamps</b><span>Created {formatDate(program.created_at)}</span><span>Locked {formatDate(program.locked_at)}</span><span>Accepted {formatDate(program.accepted_at)}</span><span>Closed {formatDate(program.closed_at)}</span></div></section></div>}
function MilestoneCard({m,program,wallet,busy,doWrite,now}){const [commit,setCommit]=useState(''),[note,setNote]=useState(''),[challenge,setChallenge]=useState(''),[response,setResponse]=useState(''),[appeal,setAppeal]=useState('');const recipient=sameAddress(wallet.account,program.recipient);const challenger=sameAddress(wallet.account,m.challenger);const canChallenge=wallet.account&&!recipient&&m.status==='SUBMITTED'&&now<=Number(m.response_deadline);const canResolve=(m.status==='SUBMITTED'||m.status==='CHALLENGED')&&now>Number(m.response_deadline);const canAppeal=m.status==='RESOLVED'&&now<=Number(m.appeal_deadline)&&(recipient||(m.has_challenge&&challenger));return <article className="milestone-card"><div className="milestone-top"><div><span className="id">MILESTONE #{m.milestone_id}</span><h3>{m.title}</h3></div><StatusPill>{m.status}</StatusPill></div><div className="criteria"><b>Locked criteria</b>{m.criteria.map((c,i)=><div key={i}><CheckCircle2 size={15}/>{c}</div>)}</div>
 {m.status==='DRAFT'&&recipient&&program.status==='ACTIVE'&&<ActionBox title="Submit exact Git commit" icon={<Send size={18}/>}><input value={commit} onChange={e=>setCommit(e.target.value)} placeholder="40 or 64 character commit SHA"/><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Submission note (argument/context only)"/><AsyncButton loading={busy==='submit_milestone'} onClick={()=>doWrite('submit_milestone',[BigInt(m.milestone_id),commit,note])}>Bind commit & submit</AsyncButton></ActionBox>}
 {m.commit_sha&&<div className="commit-box"><GitCommitLine/><div><b>{shortSha(m.commit_sha)}</b><span>{m.submission_note||'No submission note'}</span></div><a href={`https://github.com/${program.repo_id}/commit/${m.commit_sha}`} target="_blank" rel="noreferrer"><ExternalLink size={16}/></a></div>}
 {(m.status==='SUBMITTED'||m.status==='CHALLENGED')&&<div className="deadline"><Clock3 size={16}/>{now<=Number(m.response_deadline)?`Response window closes ${formatDate(m.response_deadline)}`:`Response window closed ${formatDate(m.response_deadline)}`}</div>}
 {canChallenge&&<ActionBox title="Challenge this submission" icon={<XCircle size={18}/>}><textarea value={challenge} onChange={e=>setChallenge(e.target.value)} placeholder="Explain why the locked criteria are not met…"/><AsyncButton loading={busy==='challenge_milestone'} className="danger-btn" onClick={()=>doWrite('challenge_milestone',[BigInt(m.milestone_id),challenge])}>Open challenge</AsyncButton></ActionBox>}
 {m.status==='CHALLENGED'&&<div className="argument"><b>Challenge</b><p>{m.challenge_reason}</p></div>}
 {m.status==='CHALLENGED'&&recipient&&now<=Number(m.response_deadline)&&<ActionBox title="Respond to challenge" icon={<Send size={18}/>}><textarea value={response} onChange={e=>setResponse(e.target.value)} placeholder="Respond to the challenge. This is context, not a fetch target."/><AsyncButton loading={busy==='respond_to_challenge'} onClick={()=>doWrite('respond_to_challenge',[BigInt(m.milestone_id),response])}>Submit response</AsyncButton></ActionBox>}
 {m.response_text&&<div className="argument response"><b>Recipient response</b><p>{m.response_text}</p></div>}
 {canResolve&&<ActionBox title="Resolve with GenLayer consensus" icon={<Gavel size={18}/>}><p>This write performs canonical GitHub fetches and independent nondeterministic adjudication. It can take several minutes.</p><AsyncButton loading={busy==='resolve_milestone'} onClick={()=>doWrite('resolve_milestone',[BigInt(m.milestone_id)])}>Resolve milestone</AsyncButton></ActionBox>}
 {m.status==='RESOLVED'&&<><div className="verdict"><StatusPill>{m.outcome}</StatusPill><div><b>Consensus outcome</b><p>{m.reasoning_summary}</p></div></div><div className="deadline"><Clock3 size={16}/>{now<=Number(m.appeal_deadline)?`Appeal window closes ${formatDate(m.appeal_deadline)}`:`Appeal window closed ${formatDate(m.appeal_deadline)}`}</div></>}
 {canAppeal&&<ActionBox title="Appeal this verdict" icon={<RotateCcw size={18}/>}><textarea value={appeal} onChange={e=>setAppeal(e.target.value)} placeholder="Why should a fresh round reconsider the outcome?"/><AsyncButton loading={busy==='appeal_milestone'} className="amber-btn" onClick={()=>doWrite('appeal_milestone',[BigInt(m.milestone_id),appeal])}>File appeal</AsyncButton></ActionBox>}
 {m.status==='APPEALED'&&<ActionBox title="Fresh appeal consensus" icon={<Scale size={18}/>}><p>A new round re-fetches canonical records and independently adjudicates the same locked criteria.</p><AsyncButton loading={busy==='resolve_appeal'} onClick={()=>doWrite('resolve_appeal',[BigInt(m.milestone_id)])}>Resolve appeal</AsyncButton></ActionBox>}
 {m.has_appeal&&m.appeal_outcome&&<div className="argument"><b>Appeal result: {m.appeal_outcome}</b><p>{m.appeal_reasoning_summary}</p></div>}</article>}
function ActionBox({title,icon,children}){return <div className="action-box"><div className="action-title">{icon}<b>{title}</b></div>{children}</div>};function GitCommitLine(){return <Github size={19}/>}
